apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: fairline
type: Opaque
stringData:
  DB_USER: "fairline_admin"
  DB_PASSWORD: "3HvbpncIXrv1uwyKlDEfaddv"
  JWT_SECRET: "z45vUpkEEo3lkqou5prvkGDbPwGkZLLkHOEqHJwKCwaU14LJ"
  MAIL_USERNAME: "fairlineTicket@gmail.com"
  MAIL_PASSWORD: "kudkmzqbpchhovjd"
  TOSS_SECRET_KEY: ""
